// @generated by stdf-convert-codegen from rust-stdf 1.1.0 (src/records, src/stdf_codec),
// rust-stdf-derive (RECORDS) and crates/stdf-convert/src/vur.rs.
// Do not edit: run `cargo run -p stdf-convert-codegen` to regenerate.

#![allow(clippy::upper_case_acronyms)]

use arrow_array::ArrayRef;
use arrow_schema::Field;
use rust_stdf::{StdfRecord, V1};

use super::col::{self, Column};

/// The rust-stdf version the columns were generated from.
pub const RUST_STDF_VERSION: &str = "1.1.0";

/// Every record type name, in `StdfRecord` order.
pub const RECORD_TYPES: &[&str] = &[
    "FAR",
    "ATR",
    "VUR",
    "MIR",
    "MRR",
    "PCR",
    "HBR",
    "SBR",
    "PMR",
    "PGR",
    "PLR",
    "RDR",
    "SDR",
    "PSR",
    "NMR",
    "CNR",
    "SSR",
    "CDR",
    "WIR",
    "WRR",
    "WCR",
    "PIR",
    "PRR",
    "TSR",
    "PTR",
    "MPR",
    "FTR",
    "STR",
    "BPS",
    "EPS",
    "GDR",
    "DTR",
    "RESERVED",
    "UNKNOWN",
];

/// Fields whose values are bytes (STDF `B1` and `Bn`), including `Dn` bit data and the
/// `Bn` values inside `GDR.GEN_DATA`.
pub const BYTE_FIELDS: &[&str] = &[
    "CONT_FLG",
    "OPT_FLG",
    "PART_FLG",
    "PART_FIX",
    "OPT_FLAG",
    "TEST_FLG",
    "PARM_FLG",
    "FMU_FLG",
    "RAW_DATA",
    "bit_data",
    "Bn",
];

/// Columns of `FAR` records (`rust_stdf::FAR`).
#[derive(Default)]
pub(crate) struct FARColumns {
    cpu_type: col::U1,
    stdf_ver: col::U1,
}

impl FARColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U1>::field("CPU_TYPE"),
            <col::U1>::field("STDF_VER"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::FAR) {
        self.cpu_type.append(&r.cpu_type);
        self.stdf_ver.append(&r.stdf_ver);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.cpu_type.finish(),
            self.stdf_ver.finish(),
        ]
    }
}

/// Columns of `ATR` records (`rust_stdf::ATR`).
#[derive(Default)]
pub(crate) struct ATRColumns {
    mod_tim: col::U4,
    cmd_line: col::Cn,
}

impl ATRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U4>::field("MOD_TIM"),
            <col::Cn>::field("CMD_LINE"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::ATR) {
        self.mod_tim.append(&r.mod_tim);
        self.cmd_line.append(&r.cmd_line);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.mod_tim.finish(),
            self.cmd_line.finish(),
        ]
    }
}

/// Columns of `VUR` records (`crate::Vur`).
#[derive(Default)]
pub(crate) struct VURColumns {
    upd_cnt: col::Opt<col::U1>,
    upd_nam: col::KxCn,
}

impl VURColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::Opt<col::U1>>::field("UPD_CNT"),
            <col::KxCn>::field("UPD_NAM"),
        ]
    }

    pub(crate) fn append(&mut self, r: &crate::Vur) {
        self.upd_cnt.append(&r.upd_cnt);
        self.upd_nam.append(&r.upd_nam);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.upd_cnt.finish(),
            self.upd_nam.finish(),
        ]
    }
}

/// Columns of `MIR` records (`rust_stdf::MIR`).
#[derive(Default)]
pub(crate) struct MIRColumns {
    setup_t: col::U4,
    start_t: col::U4,
    stat_num: col::U1,
    mode_cod: col::C1,
    rtst_cod: col::C1,
    prot_cod: col::C1,
    burn_tim: col::U2,
    cmod_cod: col::C1,
    lot_id: col::Cn,
    part_typ: col::Cn,
    node_nam: col::Cn,
    tstr_typ: col::Cn,
    job_nam: col::Cn,
    job_rev: col::Cn,
    sblot_id: col::Cn,
    oper_nam: col::Cn,
    exec_typ: col::Cn,
    exec_ver: col::Cn,
    test_cod: col::Cn,
    tst_temp: col::Cn,
    user_txt: col::Cn,
    aux_file: col::Cn,
    pkg_typ: col::Cn,
    famly_id: col::Cn,
    date_cod: col::Cn,
    facil_id: col::Cn,
    floor_id: col::Cn,
    proc_id: col::Cn,
    oper_frq: col::Cn,
    spec_nam: col::Cn,
    spec_ver: col::Cn,
    flow_id: col::Cn,
    setup_id: col::Cn,
    dsgn_rev: col::Cn,
    eng_id: col::Cn,
    rom_cod: col::Cn,
    serl_num: col::Cn,
    supr_nam: col::Cn,
}

impl MIRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U4>::field("SETUP_T"),
            <col::U4>::field("START_T"),
            <col::U1>::field("STAT_NUM"),
            <col::C1>::field("MODE_COD"),
            <col::C1>::field("RTST_COD"),
            <col::C1>::field("PROT_COD"),
            <col::U2>::field("BURN_TIM"),
            <col::C1>::field("CMOD_COD"),
            <col::Cn>::field("LOT_ID"),
            <col::Cn>::field("PART_TYP"),
            <col::Cn>::field("NODE_NAM"),
            <col::Cn>::field("TSTR_TYP"),
            <col::Cn>::field("JOB_NAM"),
            <col::Cn>::field("JOB_REV"),
            <col::Cn>::field("SBLOT_ID"),
            <col::Cn>::field("OPER_NAM"),
            <col::Cn>::field("EXEC_TYP"),
            <col::Cn>::field("EXEC_VER"),
            <col::Cn>::field("TEST_COD"),
            <col::Cn>::field("TST_TEMP"),
            <col::Cn>::field("USER_TXT"),
            <col::Cn>::field("AUX_FILE"),
            <col::Cn>::field("PKG_TYP"),
            <col::Cn>::field("FAMLY_ID"),
            <col::Cn>::field("DATE_COD"),
            <col::Cn>::field("FACIL_ID"),
            <col::Cn>::field("FLOOR_ID"),
            <col::Cn>::field("PROC_ID"),
            <col::Cn>::field("OPER_FRQ"),
            <col::Cn>::field("SPEC_NAM"),
            <col::Cn>::field("SPEC_VER"),
            <col::Cn>::field("FLOW_ID"),
            <col::Cn>::field("SETUP_ID"),
            <col::Cn>::field("DSGN_REV"),
            <col::Cn>::field("ENG_ID"),
            <col::Cn>::field("ROM_COD"),
            <col::Cn>::field("SERL_NUM"),
            <col::Cn>::field("SUPR_NAM"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::MIR) {
        self.setup_t.append(&r.setup_t);
        self.start_t.append(&r.start_t);
        self.stat_num.append(&r.stat_num);
        self.mode_cod.append(&r.mode_cod);
        self.rtst_cod.append(&r.rtst_cod);
        self.prot_cod.append(&r.prot_cod);
        self.burn_tim.append(&r.burn_tim);
        self.cmod_cod.append(&r.cmod_cod);
        self.lot_id.append(&r.lot_id);
        self.part_typ.append(&r.part_typ);
        self.node_nam.append(&r.node_nam);
        self.tstr_typ.append(&r.tstr_typ);
        self.job_nam.append(&r.job_nam);
        self.job_rev.append(&r.job_rev);
        self.sblot_id.append(&r.sblot_id);
        self.oper_nam.append(&r.oper_nam);
        self.exec_typ.append(&r.exec_typ);
        self.exec_ver.append(&r.exec_ver);
        self.test_cod.append(&r.test_cod);
        self.tst_temp.append(&r.tst_temp);
        self.user_txt.append(&r.user_txt);
        self.aux_file.append(&r.aux_file);
        self.pkg_typ.append(&r.pkg_typ);
        self.famly_id.append(&r.famly_id);
        self.date_cod.append(&r.date_cod);
        self.facil_id.append(&r.facil_id);
        self.floor_id.append(&r.floor_id);
        self.proc_id.append(&r.proc_id);
        self.oper_frq.append(&r.oper_frq);
        self.spec_nam.append(&r.spec_nam);
        self.spec_ver.append(&r.spec_ver);
        self.flow_id.append(&r.flow_id);
        self.setup_id.append(&r.setup_id);
        self.dsgn_rev.append(&r.dsgn_rev);
        self.eng_id.append(&r.eng_id);
        self.rom_cod.append(&r.rom_cod);
        self.serl_num.append(&r.serl_num);
        self.supr_nam.append(&r.supr_nam);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.setup_t.finish(),
            self.start_t.finish(),
            self.stat_num.finish(),
            self.mode_cod.finish(),
            self.rtst_cod.finish(),
            self.prot_cod.finish(),
            self.burn_tim.finish(),
            self.cmod_cod.finish(),
            self.lot_id.finish(),
            self.part_typ.finish(),
            self.node_nam.finish(),
            self.tstr_typ.finish(),
            self.job_nam.finish(),
            self.job_rev.finish(),
            self.sblot_id.finish(),
            self.oper_nam.finish(),
            self.exec_typ.finish(),
            self.exec_ver.finish(),
            self.test_cod.finish(),
            self.tst_temp.finish(),
            self.user_txt.finish(),
            self.aux_file.finish(),
            self.pkg_typ.finish(),
            self.famly_id.finish(),
            self.date_cod.finish(),
            self.facil_id.finish(),
            self.floor_id.finish(),
            self.proc_id.finish(),
            self.oper_frq.finish(),
            self.spec_nam.finish(),
            self.spec_ver.finish(),
            self.flow_id.finish(),
            self.setup_id.finish(),
            self.dsgn_rev.finish(),
            self.eng_id.finish(),
            self.rom_cod.finish(),
            self.serl_num.finish(),
            self.supr_nam.finish(),
        ]
    }
}

/// Columns of `MRR` records (`rust_stdf::MRR`).
#[derive(Default)]
pub(crate) struct MRRColumns {
    finish_t: col::U4,
    disp_cod: col::C1,
    usr_desc: col::Cn,
    exc_desc: col::Cn,
}

impl MRRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U4>::field("FINISH_T"),
            <col::C1>::field("DISP_COD"),
            <col::Cn>::field("USR_DESC"),
            <col::Cn>::field("EXC_DESC"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::MRR) {
        self.finish_t.append(&r.finish_t);
        self.disp_cod.append(&r.disp_cod);
        self.usr_desc.append(&r.usr_desc);
        self.exc_desc.append(&r.exc_desc);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.finish_t.finish(),
            self.disp_cod.finish(),
            self.usr_desc.finish(),
            self.exc_desc.finish(),
        ]
    }
}

/// Columns of `PCR` records (`rust_stdf::PCR`).
#[derive(Default)]
pub(crate) struct PCRColumns {
    head_num: col::U1,
    site_num: col::U1,
    part_cnt: col::U4,
    rtst_cnt: col::U4,
    abrt_cnt: col::U4,
    good_cnt: col::U4,
    func_cnt: col::U4,
}

impl PCRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U1>::field("HEAD_NUM"),
            <col::U1>::field("SITE_NUM"),
            <col::U4>::field("PART_CNT"),
            <col::U4>::field("RTST_CNT"),
            <col::U4>::field("ABRT_CNT"),
            <col::U4>::field("GOOD_CNT"),
            <col::U4>::field("FUNC_CNT"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::PCR) {
        self.head_num.append(&r.head_num);
        self.site_num.append(&r.site_num);
        self.part_cnt.append(&r.part_cnt);
        self.rtst_cnt.append(&r.rtst_cnt);
        self.abrt_cnt.append(&r.abrt_cnt);
        self.good_cnt.append(&r.good_cnt);
        self.func_cnt.append(&r.func_cnt);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.head_num.finish(),
            self.site_num.finish(),
            self.part_cnt.finish(),
            self.rtst_cnt.finish(),
            self.abrt_cnt.finish(),
            self.good_cnt.finish(),
            self.func_cnt.finish(),
        ]
    }
}

/// Columns of `HBR` records (`rust_stdf::HBR`).
#[derive(Default)]
pub(crate) struct HBRColumns {
    head_num: col::U1,
    site_num: col::U1,
    hbin_num: col::U2,
    hbin_cnt: col::U4,
    hbin_pf: col::C1,
    hbin_nam: col::Cn,
}

impl HBRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U1>::field("HEAD_NUM"),
            <col::U1>::field("SITE_NUM"),
            <col::U2>::field("HBIN_NUM"),
            <col::U4>::field("HBIN_CNT"),
            <col::C1>::field("HBIN_PF"),
            <col::Cn>::field("HBIN_NAM"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::HBR) {
        self.head_num.append(&r.head_num);
        self.site_num.append(&r.site_num);
        self.hbin_num.append(&r.hbin_num);
        self.hbin_cnt.append(&r.hbin_cnt);
        self.hbin_pf.append(&r.hbin_pf);
        self.hbin_nam.append(&r.hbin_nam);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.head_num.finish(),
            self.site_num.finish(),
            self.hbin_num.finish(),
            self.hbin_cnt.finish(),
            self.hbin_pf.finish(),
            self.hbin_nam.finish(),
        ]
    }
}

/// Columns of `SBR` records (`rust_stdf::SBR`).
#[derive(Default)]
pub(crate) struct SBRColumns {
    head_num: col::U1,
    site_num: col::U1,
    sbin_num: col::U2,
    sbin_cnt: col::U4,
    sbin_pf: col::C1,
    sbin_nam: col::Cn,
}

impl SBRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U1>::field("HEAD_NUM"),
            <col::U1>::field("SITE_NUM"),
            <col::U2>::field("SBIN_NUM"),
            <col::U4>::field("SBIN_CNT"),
            <col::C1>::field("SBIN_PF"),
            <col::Cn>::field("SBIN_NAM"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::SBR) {
        self.head_num.append(&r.head_num);
        self.site_num.append(&r.site_num);
        self.sbin_num.append(&r.sbin_num);
        self.sbin_cnt.append(&r.sbin_cnt);
        self.sbin_pf.append(&r.sbin_pf);
        self.sbin_nam.append(&r.sbin_nam);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.head_num.finish(),
            self.site_num.finish(),
            self.sbin_num.finish(),
            self.sbin_cnt.finish(),
            self.sbin_pf.finish(),
            self.sbin_nam.finish(),
        ]
    }
}

/// Columns of `PMR` records (`rust_stdf::PMR`).
#[derive(Default)]
pub(crate) struct PMRColumns {
    pmr_indx: col::U2,
    chan_typ: col::U2,
    chan_nam: col::Cn,
    phy_nam: col::Cn,
    log_nam: col::Cn,
    head_num: col::U1,
    site_num: col::U1,
}

impl PMRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U2>::field("PMR_INDX"),
            <col::U2>::field("CHAN_TYP"),
            <col::Cn>::field("CHAN_NAM"),
            <col::Cn>::field("PHY_NAM"),
            <col::Cn>::field("LOG_NAM"),
            <col::U1>::field("HEAD_NUM"),
            <col::U1>::field("SITE_NUM"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::PMR) {
        self.pmr_indx.append(&r.pmr_indx);
        self.chan_typ.append(&r.chan_typ);
        self.chan_nam.append(&r.chan_nam);
        self.phy_nam.append(&r.phy_nam);
        self.log_nam.append(&r.log_nam);
        self.head_num.append(&r.head_num);
        self.site_num.append(&r.site_num);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.pmr_indx.finish(),
            self.chan_typ.finish(),
            self.chan_nam.finish(),
            self.phy_nam.finish(),
            self.log_nam.finish(),
            self.head_num.finish(),
            self.site_num.finish(),
        ]
    }
}

/// Columns of `PGR` records (`rust_stdf::PGR`).
#[derive(Default)]
pub(crate) struct PGRColumns {
    grp_indx: col::U2,
    grp_nam: col::Cn,
    indx_cnt: col::U2,
    pmr_indx: col::KxU2,
}

impl PGRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U2>::field("GRP_INDX"),
            <col::Cn>::field("GRP_NAM"),
            <col::U2>::field("INDX_CNT"),
            <col::KxU2>::field("PMR_INDX"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::PGR) {
        self.grp_indx.append(&r.grp_indx);
        self.grp_nam.append(&r.grp_nam);
        self.indx_cnt.append(&r.indx_cnt);
        self.pmr_indx.append(&r.pmr_indx);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.grp_indx.finish(),
            self.grp_nam.finish(),
            self.indx_cnt.finish(),
            self.pmr_indx.finish(),
        ]
    }
}

/// Columns of `PLR` records (`rust_stdf::PLR`).
#[derive(Default)]
pub(crate) struct PLRColumns {
    grp_cnt: col::U2,
    grp_indx: col::KxU2,
    grp_mode: col::KxU2,
    grp_radx: col::KxU1,
    pgm_char: col::KxCn,
    rtn_char: col::KxCn,
    pgm_chal: col::KxCn,
    rtn_chal: col::KxCn,
}

impl PLRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U2>::field("GRP_CNT"),
            <col::KxU2>::field("GRP_INDX"),
            <col::KxU2>::field("GRP_MODE"),
            <col::KxU1>::field("GRP_RADX"),
            <col::KxCn>::field("PGM_CHAR"),
            <col::KxCn>::field("RTN_CHAR"),
            <col::KxCn>::field("PGM_CHAL"),
            <col::KxCn>::field("RTN_CHAL"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::PLR) {
        self.grp_cnt.append(&r.grp_cnt);
        self.grp_indx.append(&r.grp_indx);
        self.grp_mode.append(&r.grp_mode);
        self.grp_radx.append(&r.grp_radx);
        self.pgm_char.append(&r.pgm_char);
        self.rtn_char.append(&r.rtn_char);
        self.pgm_chal.append(&r.pgm_chal);
        self.rtn_chal.append(&r.rtn_chal);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.grp_cnt.finish(),
            self.grp_indx.finish(),
            self.grp_mode.finish(),
            self.grp_radx.finish(),
            self.pgm_char.finish(),
            self.rtn_char.finish(),
            self.pgm_chal.finish(),
            self.rtn_chal.finish(),
        ]
    }
}

/// Columns of `RDR` records (`rust_stdf::RDR`).
#[derive(Default)]
pub(crate) struct RDRColumns {
    num_bins: col::U2,
    rtst_bin: col::KxU2,
}

impl RDRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U2>::field("NUM_BINS"),
            <col::KxU2>::field("RTST_BIN"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::RDR) {
        self.num_bins.append(&r.num_bins);
        self.rtst_bin.append(&r.rtst_bin);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.num_bins.finish(),
            self.rtst_bin.finish(),
        ]
    }
}

/// Columns of `SDR` records (`rust_stdf::SDR`).
#[derive(Default)]
pub(crate) struct SDRColumns {
    head_num: col::U1,
    site_grp: col::U1,
    site_cnt: col::U1,
    site_num: col::KxU1,
    hand_typ: col::Cn,
    hand_id: col::Cn,
    card_typ: col::Cn,
    card_id: col::Cn,
    load_typ: col::Cn,
    load_id: col::Cn,
    dib_typ: col::Cn,
    dib_id: col::Cn,
    cabl_typ: col::Cn,
    cabl_id: col::Cn,
    cont_typ: col::Cn,
    cont_id: col::Cn,
    lasr_typ: col::Cn,
    lasr_id: col::Cn,
    extr_typ: col::Cn,
    extr_id: col::Cn,
}

impl SDRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U1>::field("HEAD_NUM"),
            <col::U1>::field("SITE_GRP"),
            <col::U1>::field("SITE_CNT"),
            <col::KxU1>::field("SITE_NUM"),
            <col::Cn>::field("HAND_TYP"),
            <col::Cn>::field("HAND_ID"),
            <col::Cn>::field("CARD_TYP"),
            <col::Cn>::field("CARD_ID"),
            <col::Cn>::field("LOAD_TYP"),
            <col::Cn>::field("LOAD_ID"),
            <col::Cn>::field("DIB_TYP"),
            <col::Cn>::field("DIB_ID"),
            <col::Cn>::field("CABL_TYP"),
            <col::Cn>::field("CABL_ID"),
            <col::Cn>::field("CONT_TYP"),
            <col::Cn>::field("CONT_ID"),
            <col::Cn>::field("LASR_TYP"),
            <col::Cn>::field("LASR_ID"),
            <col::Cn>::field("EXTR_TYP"),
            <col::Cn>::field("EXTR_ID"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::SDR) {
        self.head_num.append(&r.head_num);
        self.site_grp.append(&r.site_grp);
        self.site_cnt.append(&r.site_cnt);
        self.site_num.append(&r.site_num);
        self.hand_typ.append(&r.hand_typ);
        self.hand_id.append(&r.hand_id);
        self.card_typ.append(&r.card_typ);
        self.card_id.append(&r.card_id);
        self.load_typ.append(&r.load_typ);
        self.load_id.append(&r.load_id);
        self.dib_typ.append(&r.dib_typ);
        self.dib_id.append(&r.dib_id);
        self.cabl_typ.append(&r.cabl_typ);
        self.cabl_id.append(&r.cabl_id);
        self.cont_typ.append(&r.cont_typ);
        self.cont_id.append(&r.cont_id);
        self.lasr_typ.append(&r.lasr_typ);
        self.lasr_id.append(&r.lasr_id);
        self.extr_typ.append(&r.extr_typ);
        self.extr_id.append(&r.extr_id);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.head_num.finish(),
            self.site_grp.finish(),
            self.site_cnt.finish(),
            self.site_num.finish(),
            self.hand_typ.finish(),
            self.hand_id.finish(),
            self.card_typ.finish(),
            self.card_id.finish(),
            self.load_typ.finish(),
            self.load_id.finish(),
            self.dib_typ.finish(),
            self.dib_id.finish(),
            self.cabl_typ.finish(),
            self.cabl_id.finish(),
            self.cont_typ.finish(),
            self.cont_id.finish(),
            self.lasr_typ.finish(),
            self.lasr_id.finish(),
            self.extr_typ.finish(),
            self.extr_id.finish(),
        ]
    }
}

/// Columns of `PSR` records (`rust_stdf::PSR`).
#[derive(Default)]
pub(crate) struct PSRColumns {
    cont_flg: col::B1,
    psr_indx: col::U2,
    psr_nam: col::Cn,
    opt_flg: col::B1,
    totp_cnt: col::U2,
    locp_cnt: col::U2,
    pat_bgn: col::KxU8,
    pat_end: col::KxU8,
    pat_file: col::KxCn,
    pat_lbl: col::KxCn,
    file_uid: col::KxCn,
    atpg_dsc: col::KxCn,
    src_id: col::KxCn,
}

impl PSRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::B1>::field("CONT_FLG"),
            <col::U2>::field("PSR_INDX"),
            <col::Cn>::field("PSR_NAM"),
            <col::B1>::field("OPT_FLG"),
            <col::U2>::field("TOTP_CNT"),
            <col::U2>::field("LOCP_CNT"),
            <col::KxU8>::field("PAT_BGN"),
            <col::KxU8>::field("PAT_END"),
            <col::KxCn>::field("PAT_FILE"),
            <col::KxCn>::field("PAT_LBL"),
            <col::KxCn>::field("FILE_UID"),
            <col::KxCn>::field("ATPG_DSC"),
            <col::KxCn>::field("SRC_ID"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::PSR) {
        self.cont_flg.append(&r.cont_flg);
        self.psr_indx.append(&r.psr_indx);
        self.psr_nam.append(&r.psr_nam);
        self.opt_flg.append(&r.opt_flg);
        self.totp_cnt.append(&r.totp_cnt);
        self.locp_cnt.append(&r.locp_cnt);
        self.pat_bgn.append(&r.pat_bgn);
        self.pat_end.append(&r.pat_end);
        self.pat_file.append(&r.pat_file);
        self.pat_lbl.append(&r.pat_lbl);
        self.file_uid.append(&r.file_uid);
        self.atpg_dsc.append(&r.atpg_dsc);
        self.src_id.append(&r.src_id);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.cont_flg.finish(),
            self.psr_indx.finish(),
            self.psr_nam.finish(),
            self.opt_flg.finish(),
            self.totp_cnt.finish(),
            self.locp_cnt.finish(),
            self.pat_bgn.finish(),
            self.pat_end.finish(),
            self.pat_file.finish(),
            self.pat_lbl.finish(),
            self.file_uid.finish(),
            self.atpg_dsc.finish(),
            self.src_id.finish(),
        ]
    }
}

/// Columns of `NMR` records (`rust_stdf::NMR`).
#[derive(Default)]
pub(crate) struct NMRColumns {
    cont_flg: col::B1,
    totm_cnt: col::U2,
    locm_cnt: col::U2,
    pmr_indx: col::KxU2,
    atpg_nam: col::KxCn,
}

impl NMRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::B1>::field("CONT_FLG"),
            <col::U2>::field("TOTM_CNT"),
            <col::U2>::field("LOCM_CNT"),
            <col::KxU2>::field("PMR_INDX"),
            <col::KxCn>::field("ATPG_NAM"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::NMR) {
        self.cont_flg.append(&r.cont_flg);
        self.totm_cnt.append(&r.totm_cnt);
        self.locm_cnt.append(&r.locm_cnt);
        self.pmr_indx.append(&r.pmr_indx);
        self.atpg_nam.append(&r.atpg_nam);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.cont_flg.finish(),
            self.totm_cnt.finish(),
            self.locm_cnt.finish(),
            self.pmr_indx.finish(),
            self.atpg_nam.finish(),
        ]
    }
}

/// Columns of `CNR` records (`rust_stdf::CNR`).
#[derive(Default)]
pub(crate) struct CNRColumns {
    chn_num: col::U2,
    bit_pos: col::U4,
    cell_nam: col::Sn,
}

impl CNRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U2>::field("CHN_NUM"),
            <col::U4>::field("BIT_POS"),
            <col::Sn>::field("CELL_NAM"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::CNR) {
        self.chn_num.append(&r.chn_num);
        self.bit_pos.append(&r.bit_pos);
        self.cell_nam.append(&r.cell_nam);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.chn_num.finish(),
            self.bit_pos.finish(),
            self.cell_nam.finish(),
        ]
    }
}

/// Columns of `SSR` records (`rust_stdf::SSR`).
#[derive(Default)]
pub(crate) struct SSRColumns {
    ssr_nam: col::Cn,
    chn_cnt: col::U2,
    chn_list: col::KxU2,
}

impl SSRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::Cn>::field("SSR_NAM"),
            <col::U2>::field("CHN_CNT"),
            <col::KxU2>::field("CHN_LIST"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::SSR) {
        self.ssr_nam.append(&r.ssr_nam);
        self.chn_cnt.append(&r.chn_cnt);
        self.chn_list.append(&r.chn_list);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.ssr_nam.finish(),
            self.chn_cnt.finish(),
            self.chn_list.finish(),
        ]
    }
}

/// Columns of `CDR` records (`rust_stdf::CDR`).
#[derive(Default)]
pub(crate) struct CDRColumns {
    cont_flg: col::B1,
    cdr_indx: col::U2,
    chn_nam: col::Cn,
    chn_len: col::U4,
    sin_pin: col::U2,
    sout_pin: col::U2,
    mstr_cnt: col::U1,
    m_clks: col::KxU2,
    slav_cnt: col::U1,
    s_clks: col::KxU2,
    inv_val: col::U1,
    lst_cnt: col::U2,
    cell_lst: col::KxSn,
}

impl CDRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::B1>::field("CONT_FLG"),
            <col::U2>::field("CDR_INDX"),
            <col::Cn>::field("CHN_NAM"),
            <col::U4>::field("CHN_LEN"),
            <col::U2>::field("SIN_PIN"),
            <col::U2>::field("SOUT_PIN"),
            <col::U1>::field("MSTR_CNT"),
            <col::KxU2>::field("M_CLKS"),
            <col::U1>::field("SLAV_CNT"),
            <col::KxU2>::field("S_CLKS"),
            <col::U1>::field("INV_VAL"),
            <col::U2>::field("LST_CNT"),
            <col::KxSn>::field("CELL_LST"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::CDR) {
        self.cont_flg.append(&r.cont_flg);
        self.cdr_indx.append(&r.cdr_indx);
        self.chn_nam.append(&r.chn_nam);
        self.chn_len.append(&r.chn_len);
        self.sin_pin.append(&r.sin_pin);
        self.sout_pin.append(&r.sout_pin);
        self.mstr_cnt.append(&r.mstr_cnt);
        self.m_clks.append(&r.m_clks);
        self.slav_cnt.append(&r.slav_cnt);
        self.s_clks.append(&r.s_clks);
        self.inv_val.append(&r.inv_val);
        self.lst_cnt.append(&r.lst_cnt);
        self.cell_lst.append(&r.cell_lst);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.cont_flg.finish(),
            self.cdr_indx.finish(),
            self.chn_nam.finish(),
            self.chn_len.finish(),
            self.sin_pin.finish(),
            self.sout_pin.finish(),
            self.mstr_cnt.finish(),
            self.m_clks.finish(),
            self.slav_cnt.finish(),
            self.s_clks.finish(),
            self.inv_val.finish(),
            self.lst_cnt.finish(),
            self.cell_lst.finish(),
        ]
    }
}

/// Columns of `WIR` records (`rust_stdf::WIR`).
#[derive(Default)]
pub(crate) struct WIRColumns {
    head_num: col::U1,
    site_grp: col::U1,
    start_t: col::U4,
    wafer_id: col::Cn,
}

impl WIRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U1>::field("HEAD_NUM"),
            <col::U1>::field("SITE_GRP"),
            <col::U4>::field("START_T"),
            <col::Cn>::field("WAFER_ID"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::WIR) {
        self.head_num.append(&r.head_num);
        self.site_grp.append(&r.site_grp);
        self.start_t.append(&r.start_t);
        self.wafer_id.append(&r.wafer_id);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.head_num.finish(),
            self.site_grp.finish(),
            self.start_t.finish(),
            self.wafer_id.finish(),
        ]
    }
}

/// Columns of `WRR` records (`rust_stdf::WRR`).
#[derive(Default)]
pub(crate) struct WRRColumns {
    head_num: col::U1,
    site_grp: col::U1,
    finish_t: col::U4,
    part_cnt: col::U4,
    rtst_cnt: col::U4,
    abrt_cnt: col::U4,
    good_cnt: col::U4,
    func_cnt: col::U4,
    wafer_id: col::Cn,
    fabwf_id: col::Cn,
    frame_id: col::Cn,
    mask_id: col::Cn,
    usr_desc: col::Cn,
    exc_desc: col::Cn,
}

impl WRRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U1>::field("HEAD_NUM"),
            <col::U1>::field("SITE_GRP"),
            <col::U4>::field("FINISH_T"),
            <col::U4>::field("PART_CNT"),
            <col::U4>::field("RTST_CNT"),
            <col::U4>::field("ABRT_CNT"),
            <col::U4>::field("GOOD_CNT"),
            <col::U4>::field("FUNC_CNT"),
            <col::Cn>::field("WAFER_ID"),
            <col::Cn>::field("FABWF_ID"),
            <col::Cn>::field("FRAME_ID"),
            <col::Cn>::field("MASK_ID"),
            <col::Cn>::field("USR_DESC"),
            <col::Cn>::field("EXC_DESC"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::WRR) {
        self.head_num.append(&r.head_num);
        self.site_grp.append(&r.site_grp);
        self.finish_t.append(&r.finish_t);
        self.part_cnt.append(&r.part_cnt);
        self.rtst_cnt.append(&r.rtst_cnt);
        self.abrt_cnt.append(&r.abrt_cnt);
        self.good_cnt.append(&r.good_cnt);
        self.func_cnt.append(&r.func_cnt);
        self.wafer_id.append(&r.wafer_id);
        self.fabwf_id.append(&r.fabwf_id);
        self.frame_id.append(&r.frame_id);
        self.mask_id.append(&r.mask_id);
        self.usr_desc.append(&r.usr_desc);
        self.exc_desc.append(&r.exc_desc);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.head_num.finish(),
            self.site_grp.finish(),
            self.finish_t.finish(),
            self.part_cnt.finish(),
            self.rtst_cnt.finish(),
            self.abrt_cnt.finish(),
            self.good_cnt.finish(),
            self.func_cnt.finish(),
            self.wafer_id.finish(),
            self.fabwf_id.finish(),
            self.frame_id.finish(),
            self.mask_id.finish(),
            self.usr_desc.finish(),
            self.exc_desc.finish(),
        ]
    }
}

/// Columns of `WCR` records (`rust_stdf::WCR`).
#[derive(Default)]
pub(crate) struct WCRColumns {
    wafr_siz: col::R4,
    die_ht: col::R4,
    die_wid: col::R4,
    wf_units: col::U1,
    wf_flat: col::C1,
    center_x: col::I2,
    center_y: col::I2,
    pos_x: col::C1,
    pos_y: col::C1,
}

impl WCRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::R4>::field("WAFR_SIZ"),
            <col::R4>::field("DIE_HT"),
            <col::R4>::field("DIE_WID"),
            <col::U1>::field("WF_UNITS"),
            <col::C1>::field("WF_FLAT"),
            <col::I2>::field("CENTER_X"),
            <col::I2>::field("CENTER_Y"),
            <col::C1>::field("POS_X"),
            <col::C1>::field("POS_Y"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::WCR) {
        self.wafr_siz.append(&r.wafr_siz);
        self.die_ht.append(&r.die_ht);
        self.die_wid.append(&r.die_wid);
        self.wf_units.append(&r.wf_units);
        self.wf_flat.append(&r.wf_flat);
        self.center_x.append(&r.center_x);
        self.center_y.append(&r.center_y);
        self.pos_x.append(&r.pos_x);
        self.pos_y.append(&r.pos_y);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.wafr_siz.finish(),
            self.die_ht.finish(),
            self.die_wid.finish(),
            self.wf_units.finish(),
            self.wf_flat.finish(),
            self.center_x.finish(),
            self.center_y.finish(),
            self.pos_x.finish(),
            self.pos_y.finish(),
        ]
    }
}

/// Columns of `PIR` records (`rust_stdf::PIR`).
#[derive(Default)]
pub(crate) struct PIRColumns {
    head_num: col::U1,
    site_num: col::U1,
}

impl PIRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U1>::field("HEAD_NUM"),
            <col::U1>::field("SITE_NUM"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::PIR) {
        self.head_num.append(&r.head_num);
        self.site_num.append(&r.site_num);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.head_num.finish(),
            self.site_num.finish(),
        ]
    }
}

/// Columns of `PRR` records (`rust_stdf::PRR`).
#[derive(Default)]
pub(crate) struct PRRColumns {
    head_num: col::U1,
    site_num: col::U1,
    part_flg: col::B1,
    num_test: col::U2,
    hard_bin: col::U2,
    soft_bin: col::U2,
    x_coord: col::I2,
    y_coord: col::I2,
    test_t: col::U4,
    part_id: col::Cn,
    part_txt: col::Cn,
    part_fix: col::Bn,
}

impl PRRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U1>::field("HEAD_NUM"),
            <col::U1>::field("SITE_NUM"),
            <col::B1>::field("PART_FLG"),
            <col::U2>::field("NUM_TEST"),
            <col::U2>::field("HARD_BIN"),
            <col::U2>::field("SOFT_BIN"),
            <col::I2>::field("X_COORD"),
            <col::I2>::field("Y_COORD"),
            <col::U4>::field("TEST_T"),
            <col::Cn>::field("PART_ID"),
            <col::Cn>::field("PART_TXT"),
            <col::Bn>::field("PART_FIX"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::PRR) {
        self.head_num.append(&r.head_num);
        self.site_num.append(&r.site_num);
        self.part_flg.append(&r.part_flg);
        self.num_test.append(&r.num_test);
        self.hard_bin.append(&r.hard_bin);
        self.soft_bin.append(&r.soft_bin);
        self.x_coord.append(&r.x_coord);
        self.y_coord.append(&r.y_coord);
        self.test_t.append(&r.test_t);
        self.part_id.append(&r.part_id);
        self.part_txt.append(&r.part_txt);
        self.part_fix.append(&r.part_fix);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.head_num.finish(),
            self.site_num.finish(),
            self.part_flg.finish(),
            self.num_test.finish(),
            self.hard_bin.finish(),
            self.soft_bin.finish(),
            self.x_coord.finish(),
            self.y_coord.finish(),
            self.test_t.finish(),
            self.part_id.finish(),
            self.part_txt.finish(),
            self.part_fix.finish(),
        ]
    }
}

/// Columns of `TSR` records (`rust_stdf::TSR`).
#[derive(Default)]
pub(crate) struct TSRColumns {
    head_num: col::U1,
    site_num: col::U1,
    test_typ: col::C1,
    test_num: col::U4,
    exec_cnt: col::U4,
    fail_cnt: col::U4,
    alrm_cnt: col::U4,
    test_nam: col::Cn,
    seq_name: col::Cn,
    test_lbl: col::Cn,
    opt_flag: col::B1,
    test_tim: col::R4,
    test_min: col::R4,
    test_max: col::R4,
    tst_sums: col::R4,
    tst_sqrs: col::R4,
}

impl TSRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U1>::field("HEAD_NUM"),
            <col::U1>::field("SITE_NUM"),
            <col::C1>::field("TEST_TYP"),
            <col::U4>::field("TEST_NUM"),
            <col::U4>::field("EXEC_CNT"),
            <col::U4>::field("FAIL_CNT"),
            <col::U4>::field("ALRM_CNT"),
            <col::Cn>::field("TEST_NAM"),
            <col::Cn>::field("SEQ_NAME"),
            <col::Cn>::field("TEST_LBL"),
            <col::B1>::field("OPT_FLAG"),
            <col::R4>::field("TEST_TIM"),
            <col::R4>::field("TEST_MIN"),
            <col::R4>::field("TEST_MAX"),
            <col::R4>::field("TST_SUMS"),
            <col::R4>::field("TST_SQRS"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::TSR) {
        self.head_num.append(&r.head_num);
        self.site_num.append(&r.site_num);
        self.test_typ.append(&r.test_typ);
        self.test_num.append(&r.test_num);
        self.exec_cnt.append(&r.exec_cnt);
        self.fail_cnt.append(&r.fail_cnt);
        self.alrm_cnt.append(&r.alrm_cnt);
        self.test_nam.append(&r.test_nam);
        self.seq_name.append(&r.seq_name);
        self.test_lbl.append(&r.test_lbl);
        self.opt_flag.append(&r.opt_flag);
        self.test_tim.append(&r.test_tim);
        self.test_min.append(&r.test_min);
        self.test_max.append(&r.test_max);
        self.tst_sums.append(&r.tst_sums);
        self.tst_sqrs.append(&r.tst_sqrs);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.head_num.finish(),
            self.site_num.finish(),
            self.test_typ.finish(),
            self.test_num.finish(),
            self.exec_cnt.finish(),
            self.fail_cnt.finish(),
            self.alrm_cnt.finish(),
            self.test_nam.finish(),
            self.seq_name.finish(),
            self.test_lbl.finish(),
            self.opt_flag.finish(),
            self.test_tim.finish(),
            self.test_min.finish(),
            self.test_max.finish(),
            self.tst_sums.finish(),
            self.tst_sqrs.finish(),
        ]
    }
}

/// Columns of `PTR` records (`rust_stdf::PTR`).
#[derive(Default)]
pub(crate) struct PTRColumns {
    test_num: col::U4,
    head_num: col::U1,
    site_num: col::U1,
    test_flg: col::B1,
    parm_flg: col::B1,
    result: col::R4,
    test_txt: col::Cn,
    alarm_id: col::Cn,
    opt_flag: col::Opt<col::B1>,
    res_scal: col::Opt<col::I1>,
    llm_scal: col::Opt<col::I1>,
    hlm_scal: col::Opt<col::I1>,
    lo_limit: col::Opt<col::R4>,
    hi_limit: col::Opt<col::R4>,
    units: col::Opt<col::Cn>,
    c_resfmt: col::Opt<col::Cn>,
    c_llmfmt: col::Opt<col::Cn>,
    c_hlmfmt: col::Opt<col::Cn>,
    lo_spec: col::Opt<col::R4>,
    hi_spec: col::Opt<col::R4>,
}

impl PTRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U4>::field("TEST_NUM"),
            <col::U1>::field("HEAD_NUM"),
            <col::U1>::field("SITE_NUM"),
            <col::B1>::field("TEST_FLG"),
            <col::B1>::field("PARM_FLG"),
            <col::R4>::field("RESULT"),
            <col::Cn>::field("TEST_TXT"),
            <col::Cn>::field("ALARM_ID"),
            <col::Opt<col::B1>>::field("OPT_FLAG"),
            <col::Opt<col::I1>>::field("RES_SCAL"),
            <col::Opt<col::I1>>::field("LLM_SCAL"),
            <col::Opt<col::I1>>::field("HLM_SCAL"),
            <col::Opt<col::R4>>::field("LO_LIMIT"),
            <col::Opt<col::R4>>::field("HI_LIMIT"),
            <col::Opt<col::Cn>>::field("UNITS"),
            <col::Opt<col::Cn>>::field("C_RESFMT"),
            <col::Opt<col::Cn>>::field("C_LLMFMT"),
            <col::Opt<col::Cn>>::field("C_HLMFMT"),
            <col::Opt<col::R4>>::field("LO_SPEC"),
            <col::Opt<col::R4>>::field("HI_SPEC"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::PTR) {
        self.test_num.append(&r.test_num);
        self.head_num.append(&r.head_num);
        self.site_num.append(&r.site_num);
        self.test_flg.append(&r.test_flg);
        self.parm_flg.append(&r.parm_flg);
        self.result.append(&r.result);
        self.test_txt.append(&r.test_txt);
        self.alarm_id.append(&r.alarm_id);
        self.opt_flag.append(&r.opt_flag);
        self.res_scal.append(&r.res_scal);
        self.llm_scal.append(&r.llm_scal);
        self.hlm_scal.append(&r.hlm_scal);
        self.lo_limit.append(&r.lo_limit);
        self.hi_limit.append(&r.hi_limit);
        self.units.append(&r.units);
        self.c_resfmt.append(&r.c_resfmt);
        self.c_llmfmt.append(&r.c_llmfmt);
        self.c_hlmfmt.append(&r.c_hlmfmt);
        self.lo_spec.append(&r.lo_spec);
        self.hi_spec.append(&r.hi_spec);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.test_num.finish(),
            self.head_num.finish(),
            self.site_num.finish(),
            self.test_flg.finish(),
            self.parm_flg.finish(),
            self.result.finish(),
            self.test_txt.finish(),
            self.alarm_id.finish(),
            self.opt_flag.finish(),
            self.res_scal.finish(),
            self.llm_scal.finish(),
            self.hlm_scal.finish(),
            self.lo_limit.finish(),
            self.hi_limit.finish(),
            self.units.finish(),
            self.c_resfmt.finish(),
            self.c_llmfmt.finish(),
            self.c_hlmfmt.finish(),
            self.lo_spec.finish(),
            self.hi_spec.finish(),
        ]
    }
}

/// Columns of `MPR` records (`rust_stdf::MPR`).
#[derive(Default)]
pub(crate) struct MPRColumns {
    test_num: col::U4,
    head_num: col::U1,
    site_num: col::U1,
    test_flg: col::B1,
    parm_flg: col::B1,
    rtn_icnt: col::U2,
    rslt_cnt: col::U2,
    rtn_stat: col::KxN1,
    rtn_rslt: col::KxR4,
    test_txt: col::Cn,
    alarm_id: col::Cn,
    opt_flag: col::Opt<col::B1>,
    res_scal: col::Opt<col::I1>,
    llm_scal: col::Opt<col::I1>,
    hlm_scal: col::Opt<col::I1>,
    lo_limit: col::Opt<col::R4>,
    hi_limit: col::Opt<col::R4>,
    start_in: col::Opt<col::R4>,
    incr_in: col::Opt<col::R4>,
    rtn_indx: col::Opt<col::KxU2>,
    units: col::Opt<col::Cn>,
    units_in: col::Opt<col::Cn>,
    c_resfmt: col::Opt<col::Cn>,
    c_llmfmt: col::Opt<col::Cn>,
    c_hlmfmt: col::Opt<col::Cn>,
    lo_spec: col::Opt<col::R4>,
    hi_spec: col::Opt<col::R4>,
}

impl MPRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U4>::field("TEST_NUM"),
            <col::U1>::field("HEAD_NUM"),
            <col::U1>::field("SITE_NUM"),
            <col::B1>::field("TEST_FLG"),
            <col::B1>::field("PARM_FLG"),
            <col::U2>::field("RTN_ICNT"),
            <col::U2>::field("RSLT_CNT"),
            <col::KxN1>::field("RTN_STAT"),
            <col::KxR4>::field("RTN_RSLT"),
            <col::Cn>::field("TEST_TXT"),
            <col::Cn>::field("ALARM_ID"),
            <col::Opt<col::B1>>::field("OPT_FLAG"),
            <col::Opt<col::I1>>::field("RES_SCAL"),
            <col::Opt<col::I1>>::field("LLM_SCAL"),
            <col::Opt<col::I1>>::field("HLM_SCAL"),
            <col::Opt<col::R4>>::field("LO_LIMIT"),
            <col::Opt<col::R4>>::field("HI_LIMIT"),
            <col::Opt<col::R4>>::field("START_IN"),
            <col::Opt<col::R4>>::field("INCR_IN"),
            <col::Opt<col::KxU2>>::field("RTN_INDX"),
            <col::Opt<col::Cn>>::field("UNITS"),
            <col::Opt<col::Cn>>::field("UNITS_IN"),
            <col::Opt<col::Cn>>::field("C_RESFMT"),
            <col::Opt<col::Cn>>::field("C_LLMFMT"),
            <col::Opt<col::Cn>>::field("C_HLMFMT"),
            <col::Opt<col::R4>>::field("LO_SPEC"),
            <col::Opt<col::R4>>::field("HI_SPEC"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::MPR) {
        self.test_num.append(&r.test_num);
        self.head_num.append(&r.head_num);
        self.site_num.append(&r.site_num);
        self.test_flg.append(&r.test_flg);
        self.parm_flg.append(&r.parm_flg);
        self.rtn_icnt.append(&r.rtn_icnt);
        self.rslt_cnt.append(&r.rslt_cnt);
        self.rtn_stat.append(&r.rtn_stat);
        self.rtn_rslt.append(&r.rtn_rslt);
        self.test_txt.append(&r.test_txt);
        self.alarm_id.append(&r.alarm_id);
        self.opt_flag.append(&r.opt_flag);
        self.res_scal.append(&r.res_scal);
        self.llm_scal.append(&r.llm_scal);
        self.hlm_scal.append(&r.hlm_scal);
        self.lo_limit.append(&r.lo_limit);
        self.hi_limit.append(&r.hi_limit);
        self.start_in.append(&r.start_in);
        self.incr_in.append(&r.incr_in);
        self.rtn_indx.append(&r.rtn_indx);
        self.units.append(&r.units);
        self.units_in.append(&r.units_in);
        self.c_resfmt.append(&r.c_resfmt);
        self.c_llmfmt.append(&r.c_llmfmt);
        self.c_hlmfmt.append(&r.c_hlmfmt);
        self.lo_spec.append(&r.lo_spec);
        self.hi_spec.append(&r.hi_spec);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.test_num.finish(),
            self.head_num.finish(),
            self.site_num.finish(),
            self.test_flg.finish(),
            self.parm_flg.finish(),
            self.rtn_icnt.finish(),
            self.rslt_cnt.finish(),
            self.rtn_stat.finish(),
            self.rtn_rslt.finish(),
            self.test_txt.finish(),
            self.alarm_id.finish(),
            self.opt_flag.finish(),
            self.res_scal.finish(),
            self.llm_scal.finish(),
            self.hlm_scal.finish(),
            self.lo_limit.finish(),
            self.hi_limit.finish(),
            self.start_in.finish(),
            self.incr_in.finish(),
            self.rtn_indx.finish(),
            self.units.finish(),
            self.units_in.finish(),
            self.c_resfmt.finish(),
            self.c_llmfmt.finish(),
            self.c_hlmfmt.finish(),
            self.lo_spec.finish(),
            self.hi_spec.finish(),
        ]
    }
}

/// Columns of `FTR` records (`rust_stdf::FTR`).
#[derive(Default)]
pub(crate) struct FTRColumns {
    test_num: col::U4,
    head_num: col::U1,
    site_num: col::U1,
    test_flg: col::B1,
    opt_flag: col::B1,
    cycl_cnt: col::U4,
    rel_vadr: col::U4,
    rept_cnt: col::U4,
    num_fail: col::U4,
    xfail_ad: col::I4,
    yfail_ad: col::I4,
    vect_off: col::I2,
    rtn_icnt: col::U2,
    pgm_icnt: col::U2,
    rtn_indx: col::KxU2,
    rtn_stat: col::KxN1,
    pgm_indx: col::KxU2,
    pgm_stat: col::KxN1,
    fail_pin: col::Dn,
    vect_nam: col::Cn,
    time_set: col::Cn,
    op_code: col::Cn,
    test_txt: col::Cn,
    alarm_id: col::Cn,
    prog_txt: col::Cn,
    rslt_txt: col::Cn,
    patg_num: col::U1,
    spin_map: col::Dn,
}

impl FTRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U4>::field("TEST_NUM"),
            <col::U1>::field("HEAD_NUM"),
            <col::U1>::field("SITE_NUM"),
            <col::B1>::field("TEST_FLG"),
            <col::B1>::field("OPT_FLAG"),
            <col::U4>::field("CYCL_CNT"),
            <col::U4>::field("REL_VADR"),
            <col::U4>::field("REPT_CNT"),
            <col::U4>::field("NUM_FAIL"),
            <col::I4>::field("XFAIL_AD"),
            <col::I4>::field("YFAIL_AD"),
            <col::I2>::field("VECT_OFF"),
            <col::U2>::field("RTN_ICNT"),
            <col::U2>::field("PGM_ICNT"),
            <col::KxU2>::field("RTN_INDX"),
            <col::KxN1>::field("RTN_STAT"),
            <col::KxU2>::field("PGM_INDX"),
            <col::KxN1>::field("PGM_STAT"),
            <col::Dn>::field("FAIL_PIN"),
            <col::Cn>::field("VECT_NAM"),
            <col::Cn>::field("TIME_SET"),
            <col::Cn>::field("OP_CODE"),
            <col::Cn>::field("TEST_TXT"),
            <col::Cn>::field("ALARM_ID"),
            <col::Cn>::field("PROG_TXT"),
            <col::Cn>::field("RSLT_TXT"),
            <col::U1>::field("PATG_NUM"),
            <col::Dn>::field("SPIN_MAP"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::FTR) {
        self.test_num.append(&r.test_num);
        self.head_num.append(&r.head_num);
        self.site_num.append(&r.site_num);
        self.test_flg.append(&r.test_flg);
        self.opt_flag.append(&r.opt_flag);
        self.cycl_cnt.append(&r.cycl_cnt);
        self.rel_vadr.append(&r.rel_vadr);
        self.rept_cnt.append(&r.rept_cnt);
        self.num_fail.append(&r.num_fail);
        self.xfail_ad.append(&r.xfail_ad);
        self.yfail_ad.append(&r.yfail_ad);
        self.vect_off.append(&r.vect_off);
        self.rtn_icnt.append(&r.rtn_icnt);
        self.pgm_icnt.append(&r.pgm_icnt);
        self.rtn_indx.append(&r.rtn_indx);
        self.rtn_stat.append(&r.rtn_stat);
        self.pgm_indx.append(&r.pgm_indx);
        self.pgm_stat.append(&r.pgm_stat);
        self.fail_pin.append(&r.fail_pin);
        self.vect_nam.append(&r.vect_nam);
        self.time_set.append(&r.time_set);
        self.op_code.append(&r.op_code);
        self.test_txt.append(&r.test_txt);
        self.alarm_id.append(&r.alarm_id);
        self.prog_txt.append(&r.prog_txt);
        self.rslt_txt.append(&r.rslt_txt);
        self.patg_num.append(&r.patg_num);
        self.spin_map.append(&r.spin_map);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.test_num.finish(),
            self.head_num.finish(),
            self.site_num.finish(),
            self.test_flg.finish(),
            self.opt_flag.finish(),
            self.cycl_cnt.finish(),
            self.rel_vadr.finish(),
            self.rept_cnt.finish(),
            self.num_fail.finish(),
            self.xfail_ad.finish(),
            self.yfail_ad.finish(),
            self.vect_off.finish(),
            self.rtn_icnt.finish(),
            self.pgm_icnt.finish(),
            self.rtn_indx.finish(),
            self.rtn_stat.finish(),
            self.pgm_indx.finish(),
            self.pgm_stat.finish(),
            self.fail_pin.finish(),
            self.vect_nam.finish(),
            self.time_set.finish(),
            self.op_code.finish(),
            self.test_txt.finish(),
            self.alarm_id.finish(),
            self.prog_txt.finish(),
            self.rslt_txt.finish(),
            self.patg_num.finish(),
            self.spin_map.finish(),
        ]
    }
}

/// Columns of `STR` records (`rust_stdf::STR`).
#[derive(Default)]
pub(crate) struct STRColumns {
    cont_flg: col::B1,
    test_num: col::U4,
    head_num: col::U1,
    site_num: col::U1,
    psr_ref: col::U2,
    test_flg: col::B1,
    log_typ: col::Cn,
    test_txt: col::Cn,
    alarm_id: col::Cn,
    prog_txt: col::Cn,
    rslt_txt: col::Cn,
    z_val: col::U1,
    fmu_flg: col::B1,
    mask_map: col::Dn,
    fal_map: col::Dn,
    cyc_cnt_t: col::U8,
    totf_cnt: col::U4,
    totl_cnt: col::U4,
    cyc_base: col::U8,
    bit_base: col::U4,
    cond_cnt: col::U2,
    lim_cnt: col::U2,
    cyc_size: col::U1,
    pmr_size: col::U1,
    chn_size: col::U1,
    pat_size: col::U1,
    bit_size: col::U1,
    u1_size: col::U1,
    u2_size: col::U1,
    u3_size: col::U1,
    utx_size: col::U1,
    cap_bgn: col::U2,
    lim_indx: col::KxU2,
    lim_spec: col::KxU4,
    cond_lst: col::KxCn,
    cyc_cnt: col::U2,
    cyc_ofst: col::KxUf,
    pmr_cnt: col::U2,
    pmr_indx: col::KxUf,
    chn_cnt: col::U2,
    chn_num: col::KxUf,
    exp_cnt: col::U2,
    exp_data: col::KxU1,
    cap_cnt: col::U2,
    cap_data: col::KxU1,
    new_cnt: col::U2,
    new_data: col::KxU1,
    pat_cnt: col::U2,
    pat_num: col::KxUf,
    bpos_cnt: col::U2,
    bit_pos: col::KxUf,
    usr1_cnt: col::U2,
    usr1: col::KxUf,
    usr2_cnt: col::U2,
    usr2: col::KxUf,
    usr3_cnt: col::U2,
    usr3: col::KxUf,
    txt_cnt: col::U2,
    user_txt: col::KxCf,
}

impl STRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::B1>::field("CONT_FLG"),
            <col::U4>::field("TEST_NUM"),
            <col::U1>::field("HEAD_NUM"),
            <col::U1>::field("SITE_NUM"),
            <col::U2>::field("PSR_REF"),
            <col::B1>::field("TEST_FLG"),
            <col::Cn>::field("LOG_TYP"),
            <col::Cn>::field("TEST_TXT"),
            <col::Cn>::field("ALARM_ID"),
            <col::Cn>::field("PROG_TXT"),
            <col::Cn>::field("RSLT_TXT"),
            <col::U1>::field("Z_VAL"),
            <col::B1>::field("FMU_FLG"),
            <col::Dn>::field("MASK_MAP"),
            <col::Dn>::field("FAL_MAP"),
            <col::U8>::field("CYC_CNT_T"),
            <col::U4>::field("TOTF_CNT"),
            <col::U4>::field("TOTL_CNT"),
            <col::U8>::field("CYC_BASE"),
            <col::U4>::field("BIT_BASE"),
            <col::U2>::field("COND_CNT"),
            <col::U2>::field("LIM_CNT"),
            <col::U1>::field("CYC_SIZE"),
            <col::U1>::field("PMR_SIZE"),
            <col::U1>::field("CHN_SIZE"),
            <col::U1>::field("PAT_SIZE"),
            <col::U1>::field("BIT_SIZE"),
            <col::U1>::field("U1_SIZE"),
            <col::U1>::field("U2_SIZE"),
            <col::U1>::field("U3_SIZE"),
            <col::U1>::field("UTX_SIZE"),
            <col::U2>::field("CAP_BGN"),
            <col::KxU2>::field("LIM_INDX"),
            <col::KxU4>::field("LIM_SPEC"),
            <col::KxCn>::field("COND_LST"),
            <col::U2>::field("CYC_CNT"),
            <col::KxUf>::field("CYC_OFST"),
            <col::U2>::field("PMR_CNT"),
            <col::KxUf>::field("PMR_INDX"),
            <col::U2>::field("CHN_CNT"),
            <col::KxUf>::field("CHN_NUM"),
            <col::U2>::field("EXP_CNT"),
            <col::KxU1>::field("EXP_DATA"),
            <col::U2>::field("CAP_CNT"),
            <col::KxU1>::field("CAP_DATA"),
            <col::U2>::field("NEW_CNT"),
            <col::KxU1>::field("NEW_DATA"),
            <col::U2>::field("PAT_CNT"),
            <col::KxUf>::field("PAT_NUM"),
            <col::U2>::field("BPOS_CNT"),
            <col::KxUf>::field("BIT_POS"),
            <col::U2>::field("USR1_CNT"),
            <col::KxUf>::field("USR1"),
            <col::U2>::field("USR2_CNT"),
            <col::KxUf>::field("USR2"),
            <col::U2>::field("USR3_CNT"),
            <col::KxUf>::field("USR3"),
            <col::U2>::field("TXT_CNT"),
            <col::KxCf>::field("USER_TXT"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::STR) {
        self.cont_flg.append(&r.cont_flg);
        self.test_num.append(&r.test_num);
        self.head_num.append(&r.head_num);
        self.site_num.append(&r.site_num);
        self.psr_ref.append(&r.psr_ref);
        self.test_flg.append(&r.test_flg);
        self.log_typ.append(&r.log_typ);
        self.test_txt.append(&r.test_txt);
        self.alarm_id.append(&r.alarm_id);
        self.prog_txt.append(&r.prog_txt);
        self.rslt_txt.append(&r.rslt_txt);
        self.z_val.append(&r.z_val);
        self.fmu_flg.append(&r.fmu_flg);
        self.mask_map.append(&r.mask_map);
        self.fal_map.append(&r.fal_map);
        self.cyc_cnt_t.append(&r.cyc_cnt_t);
        self.totf_cnt.append(&r.totf_cnt);
        self.totl_cnt.append(&r.totl_cnt);
        self.cyc_base.append(&r.cyc_base);
        self.bit_base.append(&r.bit_base);
        self.cond_cnt.append(&r.cond_cnt);
        self.lim_cnt.append(&r.lim_cnt);
        self.cyc_size.append(&r.cyc_size);
        self.pmr_size.append(&r.pmr_size);
        self.chn_size.append(&r.chn_size);
        self.pat_size.append(&r.pat_size);
        self.bit_size.append(&r.bit_size);
        self.u1_size.append(&r.u1_size);
        self.u2_size.append(&r.u2_size);
        self.u3_size.append(&r.u3_size);
        self.utx_size.append(&r.utx_size);
        self.cap_bgn.append(&r.cap_bgn);
        self.lim_indx.append(&r.lim_indx);
        self.lim_spec.append(&r.lim_spec);
        self.cond_lst.append(&r.cond_lst);
        self.cyc_cnt.append(&r.cyc_cnt);
        self.cyc_ofst.append(&r.cyc_ofst);
        self.pmr_cnt.append(&r.pmr_cnt);
        self.pmr_indx.append(&r.pmr_indx);
        self.chn_cnt.append(&r.chn_cnt);
        self.chn_num.append(&r.chn_num);
        self.exp_cnt.append(&r.exp_cnt);
        self.exp_data.append(&r.exp_data);
        self.cap_cnt.append(&r.cap_cnt);
        self.cap_data.append(&r.cap_data);
        self.new_cnt.append(&r.new_cnt);
        self.new_data.append(&r.new_data);
        self.pat_cnt.append(&r.pat_cnt);
        self.pat_num.append(&r.pat_num);
        self.bpos_cnt.append(&r.bpos_cnt);
        self.bit_pos.append(&r.bit_pos);
        self.usr1_cnt.append(&r.usr1_cnt);
        self.usr1.append(&r.usr1);
        self.usr2_cnt.append(&r.usr2_cnt);
        self.usr2.append(&r.usr2);
        self.usr3_cnt.append(&r.usr3_cnt);
        self.usr3.append(&r.usr3);
        self.txt_cnt.append(&r.txt_cnt);
        self.user_txt.append(&r.user_txt);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.cont_flg.finish(),
            self.test_num.finish(),
            self.head_num.finish(),
            self.site_num.finish(),
            self.psr_ref.finish(),
            self.test_flg.finish(),
            self.log_typ.finish(),
            self.test_txt.finish(),
            self.alarm_id.finish(),
            self.prog_txt.finish(),
            self.rslt_txt.finish(),
            self.z_val.finish(),
            self.fmu_flg.finish(),
            self.mask_map.finish(),
            self.fal_map.finish(),
            self.cyc_cnt_t.finish(),
            self.totf_cnt.finish(),
            self.totl_cnt.finish(),
            self.cyc_base.finish(),
            self.bit_base.finish(),
            self.cond_cnt.finish(),
            self.lim_cnt.finish(),
            self.cyc_size.finish(),
            self.pmr_size.finish(),
            self.chn_size.finish(),
            self.pat_size.finish(),
            self.bit_size.finish(),
            self.u1_size.finish(),
            self.u2_size.finish(),
            self.u3_size.finish(),
            self.utx_size.finish(),
            self.cap_bgn.finish(),
            self.lim_indx.finish(),
            self.lim_spec.finish(),
            self.cond_lst.finish(),
            self.cyc_cnt.finish(),
            self.cyc_ofst.finish(),
            self.pmr_cnt.finish(),
            self.pmr_indx.finish(),
            self.chn_cnt.finish(),
            self.chn_num.finish(),
            self.exp_cnt.finish(),
            self.exp_data.finish(),
            self.cap_cnt.finish(),
            self.cap_data.finish(),
            self.new_cnt.finish(),
            self.new_data.finish(),
            self.pat_cnt.finish(),
            self.pat_num.finish(),
            self.bpos_cnt.finish(),
            self.bit_pos.finish(),
            self.usr1_cnt.finish(),
            self.usr1.finish(),
            self.usr2_cnt.finish(),
            self.usr2.finish(),
            self.usr3_cnt.finish(),
            self.usr3.finish(),
            self.txt_cnt.finish(),
            self.user_txt.finish(),
        ]
    }
}

/// Columns of `BPS` records (`rust_stdf::BPS`).
#[derive(Default)]
pub(crate) struct BPSColumns {
    seq_name: col::Cn,
}

impl BPSColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::Cn>::field("SEQ_NAME"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::BPS) {
        self.seq_name.append(&r.seq_name);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.seq_name.finish(),
        ]
    }
}

/// Columns of `EPS` records (`rust_stdf::EPS`).
#[derive(Default)]
pub(crate) struct EPSColumns {
}

impl EPSColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::EPS) {
        let _ = r;
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
        ]
    }
}

/// Columns of `GDR` records (`rust_stdf::GDR`).
#[derive(Default)]
pub(crate) struct GDRColumns {
    fld_cnt: col::U2,
    gen_data: col::Vn,
}

impl GDRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U2>::field("FLD_CNT"),
            <col::Vn>::field("GEN_DATA"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::GDR) {
        self.fld_cnt.append(&r.fld_cnt);
        self.gen_data.append(&r.gen_data);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.fld_cnt.finish(),
            self.gen_data.finish(),
        ]
    }
}

/// Columns of `DTR` records (`rust_stdf::DTR`).
#[derive(Default)]
pub(crate) struct DTRColumns {
    text_dat: col::Cn,
}

impl DTRColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::Cn>::field("TEXT_DAT"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::DTR) {
        self.text_dat.append(&r.text_dat);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.text_dat.finish(),
        ]
    }
}

/// Columns of `RESERVED` records (`rust_stdf::ReservedRec`).
#[derive(Default)]
pub(crate) struct RESERVEDColumns {
    typ: col::U1,
    sub: col::U1,
    byte_order: col::ByteOrder,
    raw_data: col::Bn,
}

impl RESERVEDColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U1>::field("TYP"),
            <col::U1>::field("SUB"),
            <col::ByteOrder>::field("BYTE_ORDER"),
            <col::Bn>::field("RAW_DATA"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::ReservedRec) {
        self.typ.append(&r.typ);
        self.sub.append(&r.sub);
        self.byte_order.append(&r.byte_order);
        self.raw_data.append(&r.raw_data);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.typ.finish(),
            self.sub.finish(),
            self.byte_order.finish(),
            self.raw_data.finish(),
        ]
    }
}

/// Columns of `UNKNOWN` records (`rust_stdf::ReservedRec`).
#[derive(Default)]
pub(crate) struct UNKNOWNColumns {
    typ: col::U1,
    sub: col::U1,
    byte_order: col::ByteOrder,
    raw_data: col::Bn,
}

impl UNKNOWNColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U1>::field("TYP"),
            <col::U1>::field("SUB"),
            <col::ByteOrder>::field("BYTE_ORDER"),
            <col::Bn>::field("RAW_DATA"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::ReservedRec) {
        self.typ.append(&r.typ);
        self.sub.append(&r.sub);
        self.byte_order.append(&r.byte_order);
        self.raw_data.append(&r.raw_data);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.typ.finish(),
            self.sub.finish(),
            self.byte_order.finish(),
            self.raw_data.finish(),
        ]
    }
}

/// Columns of `Dn` values (`rust_stdf::Dn`).
#[derive(Default)]
pub(crate) struct DnColumns {
    bit_count: col::U2,
    bit_data: col::Bn,
}

impl DnColumns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            <col::U2>::field("bit_count"),
            <col::Bn>::field("bit_data"),
        ]
    }

    pub(crate) fn append(&mut self, r: &rust_stdf::Dn) {
        self.bit_count.append(&r.bit_count);
        self.bit_data.append(&r.bit_data);
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.bit_count.finish(),
            self.bit_data.finish(),
        ]
    }
}

/// The position of `record`'s type in [`RECORD_TYPES`].
pub(crate) fn record_index(record: &StdfRecord) -> usize {
    match record {
        StdfRecord::FAR(_) => 0,
        StdfRecord::ATR(_) => 1,
        StdfRecord::VUR(_) => 2,
        StdfRecord::MIR(_) => 3,
        StdfRecord::MRR(_) => 4,
        StdfRecord::PCR(_) => 5,
        StdfRecord::HBR(_) => 6,
        StdfRecord::SBR(_) => 7,
        StdfRecord::PMR(_) => 8,
        StdfRecord::PGR(_) => 9,
        StdfRecord::PLR(_) => 10,
        StdfRecord::RDR(_) => 11,
        StdfRecord::SDR(_) => 12,
        StdfRecord::PSR(_) => 13,
        StdfRecord::NMR(_) => 14,
        StdfRecord::CNR(_) => 15,
        StdfRecord::SSR(_) => 16,
        StdfRecord::CDR(_) => 17,
        StdfRecord::WIR(_) => 18,
        StdfRecord::WRR(_) => 19,
        StdfRecord::WCR(_) => 20,
        StdfRecord::PIR(_) => 21,
        StdfRecord::PRR(_) => 22,
        StdfRecord::TSR(_) => 23,
        StdfRecord::PTR(_) => 24,
        StdfRecord::MPR(_) => 25,
        StdfRecord::FTR(_) => 26,
        StdfRecord::STR(_) => 27,
        StdfRecord::BPS(_) => 28,
        StdfRecord::EPS(_) => 29,
        StdfRecord::GDR(_) => 30,
        StdfRecord::DTR(_) => 31,
        StdfRecord::ReservedRec(_) => 32,
        StdfRecord::UnknownRec(_) => 33,
    }
}

/// Columns of the values in `GDR.GEN_DATA` (`rust_stdf::V1`): the value's type, and a
/// column for each type, set only in rows of that type.
#[derive(Default)]
pub(crate) struct V1Columns {
    value_type: col::Name,
    u1: col::Opt<col::U1>,
    u2: col::Opt<col::U2>,
    u4: col::Opt<col::U4>,
    i1: col::Opt<col::I1>,
    i2: col::Opt<col::I2>,
    i4: col::Opt<col::I4>,
    r4: col::Opt<col::R4>,
    r8: col::Opt<col::R8>,
    cn: col::Opt<col::Cn>,
    bn: col::Opt<col::Bn>,
    dn: col::Opt<col::Dn>,
    n1: col::Opt<col::U1>,
}

impl V1Columns {
    pub(crate) fn fields() -> Vec<Field> {
        vec![
            col::Name::field("TYPE"),
            <col::Opt<col::U1>>::field("U1"),
            <col::Opt<col::U2>>::field("U2"),
            <col::Opt<col::U4>>::field("U4"),
            <col::Opt<col::I1>>::field("I1"),
            <col::Opt<col::I2>>::field("I2"),
            <col::Opt<col::I4>>::field("I4"),
            <col::Opt<col::R4>>::field("R4"),
            <col::Opt<col::R8>>::field("R8"),
            <col::Opt<col::Cn>>::field("Cn"),
            <col::Opt<col::Bn>>::field("Bn"),
            <col::Opt<col::Dn>>::field("Dn"),
            <col::Opt<col::U1>>::field("N1"),
        ]
    }

    pub(crate) fn append(&mut self, value: &V1) {
        self.value_type.append(match value {
            V1::B0 => "B0",
            V1::U1(_) => "U1",
            V1::U2(_) => "U2",
            V1::U4(_) => "U4",
            V1::I1(_) => "I1",
            V1::I2(_) => "I2",
            V1::I4(_) => "I4",
            V1::R4(_) => "R4",
            V1::R8(_) => "R8",
            V1::Cn(_) => "Cn",
            V1::Bn(_) => "Bn",
            V1::Dn(_) => "Dn",
            V1::N1(_) => "N1",
            V1::Invalid => "Invalid",
        });
        self.u1.append_option(if let V1::U1(v) = value { Some(v) } else { None });
        self.u2.append_option(if let V1::U2(v) = value { Some(v) } else { None });
        self.u4.append_option(if let V1::U4(v) = value { Some(v) } else { None });
        self.i1.append_option(if let V1::I1(v) = value { Some(v) } else { None });
        self.i2.append_option(if let V1::I2(v) = value { Some(v) } else { None });
        self.i4.append_option(if let V1::I4(v) = value { Some(v) } else { None });
        self.r4.append_option(if let V1::R4(v) = value { Some(v) } else { None });
        self.r8.append_option(if let V1::R8(v) = value { Some(v) } else { None });
        self.cn.append_option(if let V1::Cn(v) = value { Some(v) } else { None });
        self.bn.append_option(if let V1::Bn(v) = value { Some(v) } else { None });
        self.dn.append_option(if let V1::Dn(v) = value { Some(v) } else { None });
        self.n1.append_option(if let V1::N1(v) = value { Some(v) } else { None });
    }

    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        vec![
            self.value_type.finish(),
            self.u1.finish(),
            self.u2.finish(),
            self.u4.finish(),
            self.i1.finish(),
            self.i2.finish(),
            self.i4.finish(),
            self.r4.finish(),
            self.r8.finish(),
            self.cn.finish(),
            self.bn.finish(),
            self.dn.finish(),
            self.n1.finish(),
        ]
    }
}

/// The columns of one record type.
pub(crate) enum Columns {
    FAR(Box<FARColumns>),
    ATR(Box<ATRColumns>),
    VUR(Box<VURColumns>),
    MIR(Box<MIRColumns>),
    MRR(Box<MRRColumns>),
    PCR(Box<PCRColumns>),
    HBR(Box<HBRColumns>),
    SBR(Box<SBRColumns>),
    PMR(Box<PMRColumns>),
    PGR(Box<PGRColumns>),
    PLR(Box<PLRColumns>),
    RDR(Box<RDRColumns>),
    SDR(Box<SDRColumns>),
    PSR(Box<PSRColumns>),
    NMR(Box<NMRColumns>),
    CNR(Box<CNRColumns>),
    SSR(Box<SSRColumns>),
    CDR(Box<CDRColumns>),
    WIR(Box<WIRColumns>),
    WRR(Box<WRRColumns>),
    WCR(Box<WCRColumns>),
    PIR(Box<PIRColumns>),
    PRR(Box<PRRColumns>),
    TSR(Box<TSRColumns>),
    PTR(Box<PTRColumns>),
    MPR(Box<MPRColumns>),
    FTR(Box<FTRColumns>),
    STR(Box<STRColumns>),
    BPS(Box<BPSColumns>),
    EPS(Box<EPSColumns>),
    GDR(Box<GDRColumns>),
    DTR(Box<DTRColumns>),
    RESERVED(Box<RESERVEDColumns>),
    UNKNOWN(Box<UNKNOWNColumns>),
}

impl Columns {
    pub(crate) fn new(record_type: &str) -> Option<Self> {
        Some(match record_type {
            "FAR" => Self::FAR(Box::default()),
            "ATR" => Self::ATR(Box::default()),
            "VUR" => Self::VUR(Box::default()),
            "MIR" => Self::MIR(Box::default()),
            "MRR" => Self::MRR(Box::default()),
            "PCR" => Self::PCR(Box::default()),
            "HBR" => Self::HBR(Box::default()),
            "SBR" => Self::SBR(Box::default()),
            "PMR" => Self::PMR(Box::default()),
            "PGR" => Self::PGR(Box::default()),
            "PLR" => Self::PLR(Box::default()),
            "RDR" => Self::RDR(Box::default()),
            "SDR" => Self::SDR(Box::default()),
            "PSR" => Self::PSR(Box::default()),
            "NMR" => Self::NMR(Box::default()),
            "CNR" => Self::CNR(Box::default()),
            "SSR" => Self::SSR(Box::default()),
            "CDR" => Self::CDR(Box::default()),
            "WIR" => Self::WIR(Box::default()),
            "WRR" => Self::WRR(Box::default()),
            "WCR" => Self::WCR(Box::default()),
            "PIR" => Self::PIR(Box::default()),
            "PRR" => Self::PRR(Box::default()),
            "TSR" => Self::TSR(Box::default()),
            "PTR" => Self::PTR(Box::default()),
            "MPR" => Self::MPR(Box::default()),
            "FTR" => Self::FTR(Box::default()),
            "STR" => Self::STR(Box::default()),
            "BPS" => Self::BPS(Box::default()),
            "EPS" => Self::EPS(Box::default()),
            "GDR" => Self::GDR(Box::default()),
            "DTR" => Self::DTR(Box::default()),
            "RESERVED" => Self::RESERVED(Box::default()),
            "UNKNOWN" => Self::UNKNOWN(Box::default()),
            _ => return None,
        })
    }

    /// The record's own fields, without the header columns.
    pub(crate) fn fields(record_type: &str) -> Option<Vec<Field>> {
        Some(match record_type {
            "FAR" => FARColumns::fields(),
            "ATR" => ATRColumns::fields(),
            "VUR" => VURColumns::fields(),
            "MIR" => MIRColumns::fields(),
            "MRR" => MRRColumns::fields(),
            "PCR" => PCRColumns::fields(),
            "HBR" => HBRColumns::fields(),
            "SBR" => SBRColumns::fields(),
            "PMR" => PMRColumns::fields(),
            "PGR" => PGRColumns::fields(),
            "PLR" => PLRColumns::fields(),
            "RDR" => RDRColumns::fields(),
            "SDR" => SDRColumns::fields(),
            "PSR" => PSRColumns::fields(),
            "NMR" => NMRColumns::fields(),
            "CNR" => CNRColumns::fields(),
            "SSR" => SSRColumns::fields(),
            "CDR" => CDRColumns::fields(),
            "WIR" => WIRColumns::fields(),
            "WRR" => WRRColumns::fields(),
            "WCR" => WCRColumns::fields(),
            "PIR" => PIRColumns::fields(),
            "PRR" => PRRColumns::fields(),
            "TSR" => TSRColumns::fields(),
            "PTR" => PTRColumns::fields(),
            "MPR" => MPRColumns::fields(),
            "FTR" => FTRColumns::fields(),
            "STR" => STRColumns::fields(),
            "BPS" => BPSColumns::fields(),
            "EPS" => EPSColumns::fields(),
            "GDR" => GDRColumns::fields(),
            "DTR" => DTRColumns::fields(),
            "RESERVED" => RESERVEDColumns::fields(),
            "UNKNOWN" => UNKNOWNColumns::fields(),
            _ => return None,
        })
    }

    /// Append `record`, which must be of this record type.
    pub(crate) fn append(&mut self, record: &crate::Record) {
        match (self, &record.data) {
            (Self::FAR(c), StdfRecord::FAR(r)) => c.append(r),
            (Self::ATR(c), StdfRecord::ATR(r)) => c.append(r),
            (Self::VUR(c), StdfRecord::VUR(_)) => c.append(&crate::Vur::of(record)),
            (Self::MIR(c), StdfRecord::MIR(r)) => c.append(r),
            (Self::MRR(c), StdfRecord::MRR(r)) => c.append(r),
            (Self::PCR(c), StdfRecord::PCR(r)) => c.append(r),
            (Self::HBR(c), StdfRecord::HBR(r)) => c.append(r),
            (Self::SBR(c), StdfRecord::SBR(r)) => c.append(r),
            (Self::PMR(c), StdfRecord::PMR(r)) => c.append(r),
            (Self::PGR(c), StdfRecord::PGR(r)) => c.append(r),
            (Self::PLR(c), StdfRecord::PLR(r)) => c.append(r),
            (Self::RDR(c), StdfRecord::RDR(r)) => c.append(r),
            (Self::SDR(c), StdfRecord::SDR(r)) => c.append(r),
            (Self::PSR(c), StdfRecord::PSR(r)) => c.append(r),
            (Self::NMR(c), StdfRecord::NMR(r)) => c.append(r),
            (Self::CNR(c), StdfRecord::CNR(r)) => c.append(r),
            (Self::SSR(c), StdfRecord::SSR(r)) => c.append(r),
            (Self::CDR(c), StdfRecord::CDR(r)) => c.append(r),
            (Self::WIR(c), StdfRecord::WIR(r)) => c.append(r),
            (Self::WRR(c), StdfRecord::WRR(r)) => c.append(r),
            (Self::WCR(c), StdfRecord::WCR(r)) => c.append(r),
            (Self::PIR(c), StdfRecord::PIR(r)) => c.append(r),
            (Self::PRR(c), StdfRecord::PRR(r)) => c.append(r),
            (Self::TSR(c), StdfRecord::TSR(r)) => c.append(r),
            (Self::PTR(c), StdfRecord::PTR(r)) => c.append(r),
            (Self::MPR(c), StdfRecord::MPR(r)) => c.append(r),
            (Self::FTR(c), StdfRecord::FTR(r)) => c.append(r),
            (Self::STR(c), StdfRecord::STR(r)) => c.append(r),
            (Self::BPS(c), StdfRecord::BPS(r)) => c.append(r),
            (Self::EPS(c), StdfRecord::EPS(r)) => c.append(r),
            (Self::GDR(c), StdfRecord::GDR(r)) => c.append(r),
            (Self::DTR(c), StdfRecord::DTR(r)) => c.append(r),
            (Self::RESERVED(c), StdfRecord::ReservedRec(r)) => c.append(r),
            (Self::UNKNOWN(c), StdfRecord::UnknownRec(r)) => c.append(r),
            _ => panic!("record appended to the columns of another record type"),
        }
    }

    /// Take the columns built so far, leaving them empty.
    pub(crate) fn finish(&mut self) -> Vec<ArrayRef> {
        match self {
            Self::FAR(c) => c.finish(),
            Self::ATR(c) => c.finish(),
            Self::VUR(c) => c.finish(),
            Self::MIR(c) => c.finish(),
            Self::MRR(c) => c.finish(),
            Self::PCR(c) => c.finish(),
            Self::HBR(c) => c.finish(),
            Self::SBR(c) => c.finish(),
            Self::PMR(c) => c.finish(),
            Self::PGR(c) => c.finish(),
            Self::PLR(c) => c.finish(),
            Self::RDR(c) => c.finish(),
            Self::SDR(c) => c.finish(),
            Self::PSR(c) => c.finish(),
            Self::NMR(c) => c.finish(),
            Self::CNR(c) => c.finish(),
            Self::SSR(c) => c.finish(),
            Self::CDR(c) => c.finish(),
            Self::WIR(c) => c.finish(),
            Self::WRR(c) => c.finish(),
            Self::WCR(c) => c.finish(),
            Self::PIR(c) => c.finish(),
            Self::PRR(c) => c.finish(),
            Self::TSR(c) => c.finish(),
            Self::PTR(c) => c.finish(),
            Self::MPR(c) => c.finish(),
            Self::FTR(c) => c.finish(),
            Self::STR(c) => c.finish(),
            Self::BPS(c) => c.finish(),
            Self::EPS(c) => c.finish(),
            Self::GDR(c) => c.finish(),
            Self::DTR(c) => c.finish(),
            Self::RESERVED(c) => c.finish(),
            Self::UNKNOWN(c) => c.finish(),
        }
    }
}
