from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional

__version__: str
RECORD_TYPES: List[str]

class StdfError(Exception): ...

class Reader(Iterator[Dict[str, Any]]):
    path: Path
    def __init__(self, path: str, record_types: Optional[List[str]] = ...) -> None: ...
    def __iter__(self) -> "Reader": ...
    def __next__(self) -> Dict[str, Any]: ...

def records(path: str, record_types: Optional[List[str]] = ...) -> Reader: ...
def convert(path: str, output: Optional[str] = ..., *, record_types: Optional[List[str]] = ...) -> str: ...
def run_cli(argv: List[str]) -> int: ...
