from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional, Tuple

__version__: str
RECORD_TYPES: List[str]
DEFAULT_BATCH_SIZE: int

class StdfError(Exception): ...

# Arrow objects exposing the Arrow PyCapsule interface (__arrow_c_schema__, __arrow_c_array__,
# __arrow_c_stream__), readable by pyarrow, polars, DuckDB and others.
class Batches(Iterator[Tuple[str, Any]]):
    path: Path
    def __iter__(self) -> "Batches": ...
    def __next__(self) -> Tuple[str, Any]: ...

def schema(record_type: str) -> Any: ...
def batches(path: str, record_types: Optional[List[str]] = ..., *, batch_size: int = ...) -> Batches: ...
def tables(path: str, record_types: Optional[List[str]] = ...) -> Dict[str, Any]: ...
def run_cli(argv: List[str]) -> int: ...
