[package]
name = "stdf-convert-python"
description = "Python bindings for stdf-convert"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[lib]
name = "_stdf_convert"
crate-type = ["cdylib"]

[dependencies]
stdf-convert = { path = "../crates/stdf-convert" }
pyo3 = { version = "0.29", features = ["abi3-py311"] }
pyo3-arrow = { version = "0.19", default-features = false }
arrow-array = "59"
